# Generated by Django 3.0.8 on 2020-07-10 17:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='succinct description of project', verbose_name='description')),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(), blank=True, help_text='technologies with which project was built', null=True, size=None, verbose_name='technologies')),
                ('is_completed', models.BooleanField(default=False, help_text='completion state of project', verbose_name='project completion status')),
                ('demo_url', models.URLField(default='https://', help_text='link to preview project', verbose_name='demo link')),
                ('repo_url', models.URLField(default='https://github.com/', help_text='repository url for project', verbose_name='repo link')),
                ('dated_started', models.DateField(default=django.utils.timezone.now, verbose_name='project start date')),
                ('date_completed', models.DateField(default=django.utils.timezone.now, verbose_name='date of completion')),
                ('category', models.ForeignKey(help_text='type of category project belongs to', on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('title', 'slug'), name='unique_title_and_slug'),
        ),
    ]
