# Generated by Django 3.0.8 on 2020-07-14 16:32

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import folioapps.projects.models.project
import folioapps.projects.models.screenshot


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, help_text='Preview image for project', null=True, upload_to=folioapps.projects.models.project.upload_preview_to, verbose_name='preview')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('stack', models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full stack')], help_text='Stack type for project', max_length=9, verbose_name='stack')),
                ('description', models.TextField(blank=True, help_text='Succinct description of project', verbose_name='description')),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(), blank=True, help_text='Technologies with which project was built', null=True, size=None, verbose_name='technologies')),
                ('built_with', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tools or languages that were employed to build the project', null=True, verbose_name='built with')),
                ('is_completed', models.BooleanField(default=False, help_text='Completion state of project', verbose_name='project completion status')),
                ('demo_url', models.URLField(blank=True, default='https://demo-link.com/', help_text='Link to preview project', verbose_name='demo link')),
                ('repo_url', models.URLField(default='https://github.com/', help_text='Repository url for project', verbose_name='repo link')),
                ('date_started', models.DateField(default=django.utils.timezone.now, help_text='Date project was commenced', verbose_name='project start date')),
                ('date_completed', models.DateField(default=django.utils.timezone.now, help_text='Date project was completed', verbose_name='date of completion')),
                ('category', models.ForeignKey(help_text='Type of category project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='categories.Category', verbose_name='category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=folioapps.projects.models.screenshot.upload_screenshots_to, verbose_name='image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.Project', verbose_name='project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('title', 'slug'), name='unique_title_and_slug'),
        ),
    ]
