# Generated by Django 3.0.8 on 2020-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full stack')], default=None, max_length=9, verbose_name='stack'),
            preserve_default=False,
        ),
    ]
