# Generated by Django 3.0.8 on 2020-07-13 14:46

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='project',
            name='built_with',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Tools or languages that were employed to build the project', null=True, verbose_name='built with'),
        ),
    ]
