# Generated by Django 3.0.8 on 2020-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dated_started',
            new_name='date_started',
        ),
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.ImageField(blank=True, help_text='preview image for project', null=True, upload_to='images', verbose_name='preview'),
        ),
    ]
