# Generated by Django 3.0.8 on 2020-07-10 17:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0003_auto_20200710_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(help_text='Type of category project belongs to', on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date project was completed', verbose_name='date of completion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date project was commenced', verbose_name='project start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(default='https://', help_text='Link to preview project', verbose_name='demo link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Succinct description of project', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Completion state of project', verbose_name='project completion status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(blank=True, help_text='Preview image for project', null=True, upload_to='images', verbose_name='preview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(default='https://github.com/', help_text='Repository url for project', verbose_name='repo link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full stack')], help_text='Stack type for project', max_length=9, verbose_name='stack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(), blank=True, help_text='Technologies with which project was built', null=True, size=None, verbose_name='technologies'),
        ),
    ]
